version: "3.8"
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    platform: linux/amd64 # 确保 x86 架构
    ports:
      - "27017:27017" # 开发环境保留
    volumes:
      - mongo-data:/data/db # <--- 持久化数据
    networks:
      - my-app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    platform: linux/amd64 # 确保 x86 架构
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./html:/usr/share/nginx/html
      - uploads:/usr/share/nginx/uploads # 使用更直观的路径
    depends_on:
      - backend
    networks:
      - my-app-network

  backend:
    image: my-nestjs-app:latest
    container_name: backend
    platform: linux/amd64 # 确保 x86 架构
    ports:
      - "3000:3000" # 开发环境保留
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/user
      - UPLOAD_DIR=/app/uploads
      - PORT=3000
    volumes:
      - uploads:/app/uploads # 使用 Docker 卷以简化权限管理
    depends_on:
      - mongodb
    networks:
      - my-app-network
networks:
  my-app-network:
    driver: bridge
volumes:
  uploads: # 定义 Docker 卷
  mongo-data: